// <auto-generated />
using Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Core.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230622155141_AddRoomModifiers")]
    partial class AddRoomModifiers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Hotel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Latitude", "Longitude")
                        .IsUnique();

                    b.ToTable("Hotel");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Latitude = 55.167137f,
                            Longitude = 61.379574f
                        },
                        new
                        {
                            Id = 2L,
                            Latitude = 55.16725f,
                            Longitude = 61.395924f
                        },
                        new
                        {
                            Id = 3L,
                            Latitude = 55.161903f,
                            Longitude = 61.43048f
                        });
                });

            modelBuilder.Entity("Core.Entities.Room", b =>
                {
                    b.Property<long>("HotelId")
                        .HasColumnType("bigint");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HotelId", "Number");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            HotelId = 1L,
                            Number = 1,
                            Class = "Luxe",
                            Floor = 1,
                            ImageUrl = "https://loremflickr.com/320/240?lock=1405329359",
                            Price = 9999m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 1L,
                            Number = 2,
                            Class = "Default",
                            Floor = 1,
                            ImageUrl = "https://loremflickr.com/320/240?lock=1844725699",
                            Price = 301m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 1L,
                            Number = 3,
                            Class = "VIP",
                            Floor = 1,
                            ImageUrl = "https://loremflickr.com/320/240?lock=661824766",
                            Price = 1m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 2L,
                            Number = 100,
                            Class = "Default",
                            Floor = 1,
                            ImageUrl = "https://loremflickr.com/320/240?lock=1522061971",
                            Price = 301m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 2L,
                            Number = 101,
                            Class = "Luxe",
                            Floor = 1,
                            ImageUrl = "https://loremflickr.com/320/240?lock=379889922",
                            Price = 100m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 2L,
                            Number = 200,
                            Class = "Default",
                            Floor = 2,
                            ImageUrl = "https://loremflickr.com/320/240?lock=2112474485",
                            Price = 301m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 2L,
                            Number = 201,
                            Class = "Default",
                            Floor = 2,
                            ImageUrl = "https://loremflickr.com/320/240?lock=1959292877",
                            Price = 301m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 3L,
                            Number = 10,
                            Class = "Luxe",
                            Floor = 1,
                            ImageUrl = "https://loremflickr.com/320/240?lock=389323284",
                            Price = 1111m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 3L,
                            Number = 11,
                            Class = "Default",
                            Floor = 1,
                            ImageUrl = "https://loremflickr.com/320/240?lock=387753694",
                            Price = 301m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 3L,
                            Number = 12,
                            Class = "Default",
                            Floor = 1,
                            ImageUrl = "https://loremflickr.com/320/240?lock=443725542",
                            Price = 301m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 3L,
                            Number = 20,
                            Class = "VIP",
                            Floor = 2,
                            ImageUrl = "https://loremflickr.com/320/240?lock=1517424132",
                            Price = 675656m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 3L,
                            Number = 21,
                            Class = "VIP",
                            Floor = 2,
                            ImageUrl = "https://loremflickr.com/320/240?lock=87453138",
                            Price = 19222m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 3L,
                            Number = 22,
                            Class = "Luxe",
                            Floor = 2,
                            ImageUrl = "https://loremflickr.com/320/240?lock=1819357836",
                            Price = 1m,
                            State = "Clean"
                        });
                });

            modelBuilder.Entity("Core.Entities.RoomModifier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RoomModifier");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Двуспальная кровать"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Односпальная кровать"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Питание включено"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Питание не включено"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Сейф есть"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Сейфа нет"
                        });
                });

            modelBuilder.Entity("RoomRoomModifier", b =>
                {
                    b.Property<long>("RoomModifiersId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoomsHotelId")
                        .HasColumnType("bigint");

                    b.Property<int>("RoomsNumber")
                        .HasColumnType("integer");

                    b.HasKey("RoomModifiersId", "RoomsHotelId", "RoomsNumber");

                    b.HasIndex("RoomsHotelId", "RoomsNumber");

                    b.ToTable("RoomRoomModifier", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Room", b =>
                {
                    b.HasOne("Core.Entities.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("RoomRoomModifier", b =>
                {
                    b.HasOne("Core.Entities.RoomModifier", null)
                        .WithMany()
                        .HasForeignKey("RoomModifiersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomsHotelId", "RoomsNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
