// <auto-generated />
using Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Core.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Hotel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Latitude", "Longitude")
                        .IsUnique();

                    b.ToTable("Hotel");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Latitude = 55.167137f,
                            Longitude = 61.379574f
                        },
                        new
                        {
                            Id = 2L,
                            Latitude = 55.16725f,
                            Longitude = 61.395924f
                        },
                        new
                        {
                            Id = 3L,
                            Latitude = 55.161903f,
                            Longitude = 61.43048f
                        });
                });

            modelBuilder.Entity("Core.Entities.Room", b =>
                {
                    b.Property<long>("HotelId")
                        .HasColumnType("bigint");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HotelId", "Number");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            HotelId = 1L,
                            Number = 1,
                            Class = "Luxe",
                            Floor = 1,
                            ImageUrl = "https://loremflickr.com/320/240?lock=1229780929",
                            Price = 9999m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 1L,
                            Number = 2,
                            Class = "Default",
                            Floor = 1,
                            ImageUrl = "https://loremflickr.com/320/240?lock=923646772",
                            Price = 301m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 1L,
                            Number = 3,
                            Class = "VIP",
                            Floor = 1,
                            ImageUrl = "https://loremflickr.com/320/240?lock=1356708602",
                            Price = 1m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 2L,
                            Number = 100,
                            Class = "Default",
                            Floor = 1,
                            ImageUrl = "https://loremflickr.com/320/240?lock=308339214",
                            Price = 301m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 2L,
                            Number = 101,
                            Class = "Luxe",
                            Floor = 1,
                            ImageUrl = "https://loremflickr.com/320/240?lock=943028256",
                            Price = 100m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 2L,
                            Number = 200,
                            Class = "Default",
                            Floor = 2,
                            ImageUrl = "https://loremflickr.com/320/240?lock=1640880358",
                            Price = 301m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 2L,
                            Number = 201,
                            Class = "Default",
                            Floor = 2,
                            ImageUrl = "https://loremflickr.com/320/240?lock=812584830",
                            Price = 301m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 3L,
                            Number = 10,
                            Class = "Luxe",
                            Floor = 1,
                            ImageUrl = "https://loremflickr.com/320/240?lock=446532168",
                            Price = 1111m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 3L,
                            Number = 11,
                            Class = "Default",
                            Floor = 1,
                            ImageUrl = "https://loremflickr.com/320/240?lock=1550699072",
                            Price = 301m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 3L,
                            Number = 12,
                            Class = "Default",
                            Floor = 1,
                            ImageUrl = "https://loremflickr.com/320/240?lock=1826706350",
                            Price = 301m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 3L,
                            Number = 20,
                            Class = "VIP",
                            Floor = 2,
                            ImageUrl = "https://loremflickr.com/320/240?lock=511833658",
                            Price = 675656m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 3L,
                            Number = 21,
                            Class = "VIP",
                            Floor = 2,
                            ImageUrl = "https://loremflickr.com/320/240?lock=804161671",
                            Price = 19222m,
                            State = "Clean"
                        },
                        new
                        {
                            HotelId = 3L,
                            Number = 22,
                            Class = "Luxe",
                            Floor = 2,
                            ImageUrl = "https://loremflickr.com/320/240?lock=2005243139",
                            Price = 1m,
                            State = "Clean"
                        });
                });

            modelBuilder.Entity("Core.Entities.Room", b =>
                {
                    b.HasOne("Core.Entities.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Core.Entities.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
